version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    name: rabbitmq
    driver: bridge

volumes:
  rabbitmq:
    name: rabbitmq
